#
# Makefile for CCM2200 board support
#


# Board-specific support
obj-$(CONFIG_MACH_CCM2200)      += ccm2200.o

ccm2200-objs			 = board-ccm2200.o		\
				   at91-uart-ccm2200.o		\
				   quad-uart-ccm2200.o		\
				   serial-ccm2200.o		\
